import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 2500,
    originalPrice: 5000,
    discount: 50,
    category: "Men",
    rating: 5,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 2000,
    originalPrice: 4000,
    discount: 50,
    category: "Men",
    rating: 4,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 1500,
    originalPrice: 3000,
    discount: 50,
    category: "Men",
    rating: 3,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product4-spacTrend.webp",
    finalPrice: 1000,
    originalPrice: 2000,
    discount: 50,
    category: "Men",
    rating: 5,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 500,
    originalPrice: 1000,
    discount: 50,
    category: "Men",
    rating: 4,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product2-spacTrend.webp",
    finalPrice: 5000,
    originalPrice: 10000,
    discount: 50,
    category: "Men",
    rating: 3,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 4500,
    originalPrice: 9000,
    discount: 50,
    category: "Men",
    rating: 5,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product4-spacTrend.webp",
    finalPrice: 4000,
    originalPrice: 8000,
    discount: 50,
    category: "Men",
    rating: 4,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 3500,
    originalPrice: 7000,
    discount: 50,
    category: "Men",
    rating: 3,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product2-spacTrend.webp",
    finalPrice: 3000,
    originalPrice: 6000,
    discount: 50,
    category: "Men",
    rating: 5,
    spacTrendAssured: false,
  },

  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 10000,
    originalPrice: 5000,
    discount: 50,
    category: "Women",
    rating: 5,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 9000,
    originalPrice: 5000,
    discount: 50,
    category: "Women",
    rating: 4,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 8000,
    originalPrice: 5000,
    discount: 50,
    category: "Women",
    rating: 3,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product4-spacTrend.webp",
    finalPrice: 7000,
    originalPrice: 5000,
    discount: 50,
    category: "Women",
    rating: 5,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 6000,
    originalPrice: 5000,
    discount: 50,
    category: "Women",
    rating: 4,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product2-spacTrend.webp",
    finalPrice: 5000,
    originalPrice: 5000,
    discount: 50,
    category: "Women",
    rating: 3,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 4000,
    originalPrice: 5000,
    discount: 50,
    category: "Women",
    rating: 5,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product4-spacTrend.webp",
    finalPrice: 3000,
    originalPrice: 5000,
    discount: 50,
    category: "Women",
    rating: 4,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 2000,
    originalPrice: 5000,
    discount: 50,
    category: "Women",
    rating: 3,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product2-spacTrend.webp",
    finalPrice: 1000,
    originalPrice: 5000,
    discount: 50,
    category: "Women",
    rating: 5,
    spacTrendAssured: false,
  },

  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 2500,
    originalPrice: 5000,
    discount: 50,
    category: "Kids",
    rating: 5,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 2000,
    originalPrice: 4000,
    discount: 50,
    category: "Kids",
    rating: 4,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 1500,
    originalPrice: 3000,
    discount: 50,
    category: "Kids",
    rating: 3,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product4-spacTrend.webp",
    finalPrice: 1000,
    originalPrice: 2000,
    discount: 50,
    category: "Kids",
    rating: 5,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 500,
    originalPrice: 1000,
    discount: 50,
    category: "Kids",
    rating: 4,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product2-spacTrend.webp",
    finalPrice: 5000,
    originalPrice: 10000,
    discount: 50,
    category: "Kids",
    rating: 3,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 4500,
    originalPrice: 9000,
    discount: 50,
    category: "Kids",
    rating: 5,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product4-spacTrend.webp",
    finalPrice: 4000,
    originalPrice: 8000,
    discount: 50,
    category: "Kids",
    rating: 4,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 3500,
    originalPrice: 7000,
    discount: 50,
    category: "Kids",
    rating: 3,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product2-spacTrend.webp",
    finalPrice: 3000,
    originalPrice: 6000,
    discount: 50,
    category: "Kids",
    rating: 5,
    spacTrendAssured: false,
  },

  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 2500,
    originalPrice: 5000,
    discount: 50,
    category: "Home&Living",
    rating: 5,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 2000,
    originalPrice: 4000,
    discount: 50,
    category: "Home&Living",
    rating: 4,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 1500,
    originalPrice: 3000,
    discount: 50,
    category: "Home&Living",
    rating: 3,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product4-spacTrend.webp",
    finalPrice: 1000,
    originalPrice: 2000,
    discount: 50,
    category: "Home&Living",
    rating: 5,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 500,
    originalPrice: 1000,
    discount: 50,
    category: "Home&Living",
    rating: 4,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product2-spacTrend.webp",
    finalPrice: 5000,
    originalPrice: 10000,
    discount: 50,
    category: "Home&Living",
    rating: 3,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 4500,
    originalPrice: 9000,
    discount: 50,
    category: "Home&Living",
    rating: 5,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product4-spacTrend.webp",
    finalPrice: 4000,
    originalPrice: 8000,
    discount: 50,
    category: "Home&Living",
    rating: 4,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 3500,
    originalPrice: 7000,
    discount: 50,
    category: "Home&Living",
    rating: 3,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product2-spacTrend.webp",
    finalPrice: 3000,
    originalPrice: 6000,
    discount: 50,
    category: "Home&Living",
    rating: 5,
    spacTrendAssured: false,
  },

  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 2500,
    originalPrice: 5000,
    discount: 50,
    category: "Beauty",
    rating: 5,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 2000,
    originalPrice: 4000,
    discount: 50,
    category: "Beauty",
    rating: 4,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 1500,
    originalPrice: 3000,
    discount: 50,
    category: "Beauty",
    rating: 3,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product4-spacTrend.webp",
    finalPrice: 1000,
    originalPrice: 2000,
    discount: 50,
    category: "Beauty",
    rating: 5,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 500,
    originalPrice: 1000,
    discount: 50,
    category: "Beauty",
    rating: 4,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product2-spacTrend.webp",
    finalPrice: 5000,
    originalPrice: 10000,
    discount: 50,
    category: "Beauty",
    rating: 3,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product3-spacTrend.webp",
    finalPrice: 4500,
    originalPrice: 9000,
    discount: 50,
    category: "Beauty",
    rating: 5,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product4-spacTrend.webp",
    finalPrice: 4000,
    originalPrice: 8000,
    discount: 50,
    category: "Beauty",
    rating: 4,
    spacTrendAssured: false,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product1-spacTrend.webp",
    finalPrice: 3500,
    originalPrice: 7000,
    discount: 50,
    category: "Beauty",
    rating: 3,
    spacTrendAssured: true,
  },
  {
    _id: uuid(),
    title: "Campus Sutra",
    subtitle: "Solid Hooded Sweatshirt",
    imageUrl: "asset/product2-spacTrend.webp",
    finalPrice: 3000,
    originalPrice: 6000,
    discount: 50,
    category: "Beauty",
    rating: 5,
    spacTrendAssured: false,
  },
];
